### ISSUE TITLE
侧边栏遮挡图片

### ISSUE THREAD

**Issue by sjt-2024** [sjt-2024/tgyz2602#2]
打开侧边栏,然后打开图片,有一部分会被侧边栏挡住
![image](https://github.com/user-attachments/assets/639407f7-92c6-423a-8746-b022d9e765bb)

**Comment by Minemetero** [comment]
很好的提议 :)

**Comment by lingbopro** [comment]
因为图片查看我用的Dialog，估计是Sober的特性

**Comment by sjt-2024** [comment]
你就打开图片时自动隐藏侧栏(或者默认隐藏它

**Comment by Minemetero** [comment]
> 你就打开图片时自动隐藏侧栏(或者默认隐藏它

我正在尝试实现

**Comment by Minemetero** [comment]
![image_2024-08-11_214039371](https://github.com/user-attachments/assets/be175284-8a62-4288-b3db-85feff6e74e4)
玩坏了

**Comment by lingbopro** [comment]
把图片查看的对话框的`z-index`设高点就行了

**Comment by Minemetero** [comment]
别改了，我功能实现了

**Comment by lingbopro** [comment]
@Minemetero 你这实现方式有大问题，一旦点了侧边栏切换键就会整个白屏

**Comment by lingbopro** [comment]
你有没有看Sober文档啊，直接把左栏设hidden，Sober有提供`toggle`方法的啊…

**Comment by lingbopro** [comment]
而且你设的还不是左栏，还是整个抽屉，主内容是包裹在抽屉元素里的啊…得回退

**Comment by sjt-2024** [comment]
ah? @lingbopro  你有旧版本备份?

**Comment by lingbopro** [comment]
我本地的还是旧版本

**Comment by lingbopro** [comment]
而且git可以从提交创建分支的

**Comment by lingbopro** [comment]
回退玩了
这git气死我了

**Comment by lingbopro** [comment]
我找到解决方法了
只需要把`div#tooltips`移到主体div外面就行了

**Comment by lingbopro** [comment]
搞定

**Comment by Minemetero** [comment]
无脑做的

**Comment by Minemetero** [comment]
代码能跑就行 :)

**Comment by lingbopro** [comment]
> 代码能跑就行 :)

你这属于是能跑但是根本用不了
